name: AI Swing Trading Scanner

on:
  schedule:
    # Every 15 minutes
    - cron: "*/15 * * * *"

  workflow_dispatch:

jobs:
  run-scanner:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Scanner
        run: |
          python app/scanner/run_scanner.py

      - name: Commit Updated Database
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          git add .

          git diff --cached --quiet || git commit -m "Auto scanner update"

          git push